services:
  proxy:
    image: caddy:2.10.2-alpine
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3001
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./data:/app/data
